Repository h-yoshikawa44/ooui-memo, pull requests merged in 2021-02, with the labels that each got.

#18 Laravel認証機構周りの設計と実体を一致させる
  docs/api/reference/ooui-memo.v1.yaml
  docs/erd.vuerd.json
  src/app/User.php
  src/composer.json
  src/composer.lock
  src/database/migrations/2014_10_12_000000_create_users_table.php
  src/database/migrations/2014_10_12_100000_create_password_resets_table.php
  src/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
Labels: basic design

#21 Remote Container設定の見直し
  .devcontainer/devcontainer.json
  .vscode/settings.json
  README.md
  ooui-memo.code-workspace
Labels: environment

#23 ロケール日本語対応
  src/.editorconfig
  src/config/app.php
  src/resources/lang/ja.json
  src/resources/lang/ja/auth.php
  src/resources/lang/ja/pagination.php
  src/resources/lang/ja/passwords.php
  src/resources/lang/ja/validation.php
Labels: enhancement

#25 パスワードリセット機能が動作するようにする
  docker-compose.yml
  docs/desktop.drawio.png
  docs/mobile.drawio.png
  docs/screen/app/memo.drawio.svg
  docs/screen/auth/login.drawio.svg
  docs/screen/auth/password-reset-mail.drawio.svg
  docs/screen/auth/password-reset.drawio.svg
  docs/screen/auth/register.drawio.svg
  docs/screen/desktop.drawio.svg
  docs/screen/mobile.drawio.svg
  src/.env.example
  src/resources/lang/ja.json
  src/resources/views/vendor/notifications/email.blade.php
Labels: environment

#26 Heroku環境のセットアップ
  .devcontainer/devcontainer.json
  README.md
  docs/architecture.png
  docs/architecture.svg
  src/.heroku/nginx/default.conf
  src/.node-version
  src/Procfile
  src/app/Providers/AppServiceProvider.php
  src/composer.json
  src/composer.lock
Labels: environment

#28 GitHub Actions設定
  .github/workflows/develop.yml
  .github/workflows/production.yml
  Makefile
  src/package.json
  src/phpcs.xml
  src/tests/Feature/ExampleTest.php
  src/webpack.mix.js
Labels: environment
